# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LegendDataFilterPlugin
                                 A QGIS plugin
 No Description yet
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-07-17
        copyright            : (C) 2019 by Omar Khan
        email                : omar.khan+qgis@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LegendDataFilterPlugin class from file LegendDataFilterPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .legend_data_filter import LegendDataFilterPlugin
    return LegendDataFilterPlugin(iface)
